# Generated by Django 3.2 on 2023-01-26 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=255)),
                ('media_count', models.IntegerField(null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.TextField()),
                ('media', models.ImageField(upload_to='')),
                ('media_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
    ]
