# Generated by Django 3.2 on 2023-01-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='access_token',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='profile_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
