# Generated by Django 3.2 on 2023-01-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230128_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='media',
        ),
        migrations.AddField(
            model_name='media',
            name='media_url',
            field=models.URLField(default=''),
        ),
    ]
