# Generated by Django 3.2 on 2023-01-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230128_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_url',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
