# Generated by Django 3.2 on 2023-01-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_media_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='post_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='profile_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='account_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
